CREATE TABLE sotrudniki
(
    id               int4    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1),
    name             varchar NOT NULL,
    surname          varchar NOT NULL,
    phone            varchar NOT NULL,
    company_id       varchar NOT NULL,
    passport_type    varchar NOT NULL,
    passport_number  varchar NOT NULL,
    department_name  varchar NOT NULL,
    department_phone varchar NOT NULL,
    CONSTRAINT sotrudniki_pkey PRIMARY KEY (id) /* устанавливаем ограничение на столбец id,
                                                   это первичный ключ который будет уникальным*/
    /*внешний ключ(department_id) ссылается на столбец
   id  в "родительской" таблице + добавлем ограничение,
   что значения внешнего ключа будут ссылаться только на
   существующие значения в стбце id в родительской таблице*/

);









